[tool.poetry]
name = "ssd1306_display"
version = "0.1.0"
description = ""
authors = ["Greg Smith <me@gregsmith.nyc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
